name: Publish Python 🐍 distributions 📦 to PyPI

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pypa/build
      run: python -m pip install --upgrade build
    - name: Build source and wheel distributions
      run: python -m build --sdist --wheel --outdir dist/ .
    - name: Publish distributions to PyPI
      uses: pypa/gh-action-pypi-publish@v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}